### ISSUE TITLE
Update Vendor - scssphp

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-customizer#65]
### Description

Our version of scssphp is quite out of date 0.8.4 the current version is [1.4.1](https://github.com/scssphp/scssphp/blob/master/src/Version.php). We need to update the vendor using composer, and test to see if the CSS generates when you "Publish" via the customizer.

### TODO

- [ ] Update the vendor
- [ ] Open up the publisher, and make some changes to the settings.
- [ ] Click publish,  if successful the page will save.
- [ ] If no you will need to open up the debug console, and see what the error being returned is.

### Reference links:

https://scssphp.github.io/scssphp/
https://github.com/scssphp/scssphp/
https://github.com/scssphp/scssphp/releases
